name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: isEven
        with:
          number: 12
      - run: |
          printf '%s\n' "Is my number even? ${{ steps.isEven.outputs.is_even }}!"